apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus_ds
    access: proxy
    url: http://prometheus:9090 # Matches service name 'prometheus'
    isDefault: true
    jsonData:
      httpMethod: GET

  - name: Loki
    type: loki
    uid: loki_ds
    access: proxy
    url: http://loki:3100 # Matches service name 'loki'
    jsonData:
      derivedFields:
        - datasourceUid: 'tempo_ds'
          matcherRegex: 'trace_id=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'

  - name: Tempo
    type: tempo
    uid: tempo_ds
    access: proxy
    url: http://tempo:3200 # Matches service name 'tempo'
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki_ds'
        tags: ['job', 'instance']
        mappedTags: [{ key: 'service.name', value: 'job' }]
        filterByTraceID: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'