# promtail/promtail-config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      filters:
        - name: network
          # CHANGED: Update this to match your Swarm Stack name
          values: [crypto_stack_app-net, crypto_stack_db-net]
  relabel_configs:
    # Use the container name as the 'job' label
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'job'
    # Use the container name as the 'instance' label
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'instance'