# promtail/promtail-config.prod.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: swarm_logs
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s

  relabel_configs:
    # 1. Try to set 'job' to the Swarm Service Name
    - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
      regex: '(.+)'
      target_label: 'job'
    
    # 2. If Swarm Name is empty (non-swarm containers), fallback to Container Name
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container_name'
    
    # 3. Add the Stack Name as a label if available
    - source_labels: ['__meta_docker_container_label_com_docker_stack_namespace']
      target_label: 'stack'